server:
  port: 8082
  servlet:
    context-path: /provider
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 47.93.251.190:8848
      config:
        server-addr: 47.93.251.190:8848
lizi:
  providerValue: 1234
