server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # git仓库地址
          uri: https://github.com/liziczh/lizi-springcloud
          # git分支
          default-label: master
          # 配置文件根目录
          search-paths: springcloud-config/config
#          username: liziczh  # 公开项目，无需配置
#          password: xxxxxx   # 公开项目，无需配置
