server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liziczh/lizi-springcloud  # git仓库地址
          default-label: master # git分支
          search-paths: springcloud-config/config # 配置文件根目录
#          username: liziczh  # 公开项目，无需配置
#          password: xxxxxx   # 公开项目，无需配置
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/  # 单机
#      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/,http://localhost:8003/eureka/ # 集群
