server:
  port: 8003
spring:
  application:
    name: eureka-server
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      default-zone: http://peer1:8001/eureka/,http://peer2:8002/eureka/
