server:
  port: 8071
spring:
  application:
    name: gateway-service-a
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # 启用注册中心定位网关服务，启用后可直接使用应用名程调用服务
      routes:
        # 路由标识
        id: eureka-service-provider
        # 目标服务URL
        uri: http://localhost:8072/
        # 断言
        predicates:
          Path= /hello
