server:
  port: 8501
spring:
  application:
    name: consul-producer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        hostname: localhost
        service-name: consul-producer
        health-check-path: /actuator/health
        health-check-interval: 15s
