server:
  port: 8081
  servlet:
    context-path: /consumer
spring:
  application:
    name: nacos-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 47.93.251.190:8848
      config:
        server-addr: 47.93.251.190:8848
